### ISSUE TITLE
Issue Evolvere Light Aurorae

### ISSUE THREAD

**Issue by MichaelTiebesl** [franksouza183/EvolvereSuit#37]
When i click on the button to maximize it for example i get a black space.
I have this only with the Evolvere light Aurorae theme. Other themes have not this issue.
Do you know what it can be?

Thanks for your time.

![kvantum](https://cloud.githubusercontent.com/assets/10792019/6550379/351f3798-c661-11e4-8362-db9f19c9d244.png)
![kvantum1](https://cloud.githubusercontent.com/assets/10792019/6550380/3a37f116-c661-11e4-9ed8-69bf7f7c2e05.png)
![kvantum2](https://cloud.githubusercontent.com/assets/10792019/6550381/3fc20ca2-c661-11e4-9b28-93985a0d7006.png)

**Comment by franksouza183** [comment]
I didn't get it. The maximize button becomes black, or the window contents?

**Comment by franksouza183** [comment]
Oh, sorry, I thought you had designed this black area, this needs to be corrected urgently. I will investigate as soon as possible.

**Comment by franksouza183** [comment]
I committed some changes / improvements in the aurorae theme, I hope it fixed because I couldn't reproduce the problem here. I'll leave the issue open until I was sure the problem is gone.

**Comment by MichaelTiebesl** [comment]
Thanks for some changes and for sure the improvements. It is looking better now. Only the issue from me is still the same.

**Comment by franksouza183** [comment]
Could you tell me the theme name that is ok? Other than the default one

**Comment by MichaelTiebesl** [comment]
So far only the default ones are working with me. I tested around 5 themes but the same issue as with Evolvere.

**Comment by franksouza183** [comment]
Could you do a test? Copy the default theme to another, with a different name, you must also edit the metada.desktop file. If this works, I will try to draw the theme based on the default.

**Comment by MichaelTiebesl** [comment]
I will do it soon as possible. First i have to found out where everything is here in plasma5. Before in KDE4 it was easy to found my themes and icons but plasma5 is a bit different.

**Comment by MichaelTiebesl** [comment]
Looks like there is a bug in Plasma5 itself: https://forum.kde.org/viewtopic.php?f=289&t=125268

**Comment by franksouza183** [comment]
Ok, closing this issue... Thanks for the info
